export const SET_MULTILINE_WIDTH = 'SET_MULTILINE_WIDTH'

// basic game
export const ANIMATE_PREVIEW_START = 'ANIMATE_PREVIEW_START'
export const ANIMATE_PREVIEW_END = 'ANIMATE_PREVIEW_END'
export const SELECT_EXERCISE = 'SELECT_EXERCISE'
export const TOGGLE_CODONS = 'TOGGLE_CODONS'
export const TOGGLE_ADMIN_EVALUATION = 'TOGGLE_ADMIN_EVALUATION'
export const EDITING_GAME_INPUT = 'EDITING_GAME_INPUT'

// admin exercise CRUD
export const FETCH_EXERCISES_INIT = 'FETCH_EXERCISES_INIT'
export const FETCH_EXERCISES_SUCCESS = 'FETCH_EXERCISES_SUCCESS'
export const FETCHED_EXERCISES_FROM_CACHED = 'FETCHED_EXERCISES_FROM_CACHED'
export const ADD_EXERCISE = 'ADD_EXERCISE'
export const ADD_EXERCISE_INIT = 'ADD_EXERCISE_INIT'
export const ADD_EXERCISE_SUCCESS = 'ADD_EXERCISE_SUCCESS'
export const ADD_EXERCISE_FAIL = 'ADD_EXERCISE_FAIL§'
export const UPDATE_EXERCISE = 'UPDATE_EXERCISE'
export const UPDATE_EXERCISE_INIT = 'UPDATE_EXERCISE_INIT'
export const UPDATE_EXERCISE_SUCCESS = 'UPDATE_EXERCISE_SUCCESS'
export const UPDATE_EXERCISE_FAIL = 'UPDATE_EXERCISE_FAIL'
export const DELETE_EXERCISE = 'DELETE_EXERCISE'
export const DELETE_EXERCISE_INIT = 'DELETE_EXERCISE_INIT'
export const DELETE_EXERCISE_SUCCESS = 'DELETE_EXERCISE_SUCCESS'
export const DELETE_EXERCISE_FAIL = 'DELETE_EXERCISE_FAIL'
export const EXERCISE_DOESNT_EXIST = 'EXERCISE_DOESNT_EXIST'

// notifications
export const NOTIFY_DELETED = 'NOTIFY_DELETED'

// admin filters
export const FILTER_EXERCISES_BY_TEXT = 'FILTER_EXERCISES_BY_TEXT'
export const SORT_EXERCISES_BY = 'SORT_EXERCISES_BY'
export const SHOW_LOGGED_IN_AUTHOR_EXERCISES_ONLY = 'SHOW_LOGGED_IN_AUTHOR_EXERCISES_ONLY'

// authentication
export const LOGGED_IN_ADMIN = 'LOGGED_IN_ADMIN'
export const LOGGED_OUT_ADMIN = 'LOGGED_OUT_ADMIN'

// Author info
export const FETCH_AUTHORS_INIT = 'FETCH_AUTHORS_INIT'
export const FETCH_AUTHORS_SUCCESS = 'FETCH_AUTHORS_SUCCESS'
export const UPDATE_AUTHOR_NAME = 'UPDATE_AUTHOR_NAME'
export const UPDATE_AUTHOR_NAME_FAIL = 'UPDATE_AUTHOR_NAME_FAIL'

// Cohorts info
export const FETCH_COHORTS_INIT = 'FETCH_COHORTS_INIT'
export const FETCH_COHORTS_SUCCESS = 'FETCH_COHORTS_SUCCESS'
export const FETCH_COHORT_STUDENT_INTERFACE_INIT = 'FETCH_COHORT_STUDENT_INTERFACE_INIT'
export const FETCH_COHORT_STUDENT_INTERFACE_SUCCESS = 'FETCH_COHORT_STUDENT_INTERFACE_SUCCESS'
export const FETCH_COHORT_INIT = 'FETCH_COHORT_INIT'
export const FETCH_COHORT_SUCCESS = 'FETCH_COHORT_SUCCESS'
export const ADD_COHORT_INIT = 'ADD_COHORT_INIT'
export const ADD_COHORT_SUCCESS = 'ADD_COHORT_SUCCESS'
export const ADD_COHORT_FAIL = 'ADD_COHORT_FAIL'
export const REMOVE_COHORT_INIT = 'REMOVE_COHORT_INIT'
export const REMOVE_COHORT_SUCCESS = 'REMOVE_COHORT_SUCCESS'
export const UPDATE_COHORT_NAME_INIT = 'UPDATE_COHORT_NAME_INIT'
export const UPDATE_COHORT_NAME_SUCCESS = 'UPDATE_COHORT_NAME_SUCCESS'


export const ADD_COHORT_EXERCISE_INIT = 'ADD_COHORT_EXERCISE_INIT'
export const ADD_COHORT_EXERCISE_SUCCESS = 'ADD_COHORT_EXERCISE_SUCCESS'

export const REMOVE_COHORT_EXERCISE_INIT = 'REMOVE_COHORT_EXERCISE_INIT'
export const REMOVE_COHORT_EXERCISE_SUCCESS = 'REMOVE_COHORT_EXERCISE_SUCCESS'

// Students info
export const FETCH_STUDENTS_INIT = 'FETCH_STUDENTS_INIT'
export const UPDATE_CURRENT_STUDENT_ID = 'UPDATE_CURRENT_STUDENT_ID'
export const FETCH_STUDENTS_SUCCESS = 'FETCH_STUDENTS_SUCCESS'
export const FETCH_STUDENT_INIT = 'FETCH_STUDENT_INIT'
export const FETCH_STUDENT_SUCCESS = 'FETCH_STUDENT_SUCCESS'
export const ADD_STUDENT_INIT = 'ADD_STUDENT_INIT'
export const ADD_STUDENT_SUCCESS = 'ADD_STUDENT_SUCCESS'
export const ADD_STUDENT_FAIL = 'ADD_STUDENT_FAIL'
export const REMOVE_STUDENT_INIT = 'REMOVE_STUDENT_INIT'
export const REMOVE_STUDENT_SUCCESS = 'REMOVE_STUDENT_SUCCESS'
export const REMOVE_STUDENT_FAIL = 'REMOVE_STUDENT_FAIL'
export const UPDATE_STUDENT_FULLNAME_INIT = 'UPDATE_STUDENT_FULLNAME_INIT'
export const UPDATE_STUDENT_FULLNAME_SUCCESS = 'UPDATE_STUDENT_FULLNAME_SUCCESS'
export const UPDATE_STUDENT_FULLNAME_FAIL = 'UPDATE_STUDENT_FULLNAME_FAIL'
export const CHECK_STUDENT_EXISTS = 'CHECK_STUDENT_EXISTS'
export const STUDENT_DOESNT_EXIST = 'STUDENT_DOESNT_EXIST'
export const STUDENT_ALREADY_EXISTS = 'STUDENT_ALREADY_EXISTS'

// Progression through an exercise
export const NOT_COUNTING_ATTEMPT = 'NOT_COUNTING_ATTEMPT'
export const EXERCISE_FAIL = 'EXERCISE_FAIL'
export const PHASE_1_COMPLETE = 'PHASE_1_COMPLETE'
export const EXERCISE_COMPLETION_INIT = 'EXERCISE_COMPLETION_INIT'
export const EXERCISE_COMPLETION_SUCCESS = 'EXERCISE_COMPLETION_SUCCESS'
export const SEND_ADVICE_MESSAGE_INIT = 'SEND_ADVICE_MESSAGE_INIT'
export const SEND_ADVICE_MESSAGE_SUCCESS = 'SEND_ADVICE_MESSAGE_SUCCESS'
export const SEND_ADVICE_MESSAGE_FAIL = 'SEND_ADVICE_MESSAGE_FAIL'
export const VIEW_TRANSFORMED_EXERCISE = 'VIEW_TRANSFORMED_EXERCISE'