export const SET_MULTILINE_WIDTH = 'SET_MULTILINE_WIDTH'

export const ANIMATE_PREVIEW_START = 'ANIMATE_PREVIEW_START'
export const ANIMATE_PREVIEW_END = 'ANIMATE_PREVIEW_END'
export const FETCH_EXERCISES_INIT = 'FETCH_EXERCISES_INIT'
export const FETCH_EXERCISES_SUCCESS = 'FETCH_EXERCISES_SUCCESS'
export const FETCHED_EXERCISES_FROM_CACHED = 'FETCHED_EXERCISES_FROM_CACHED'
export const SELECT_EXERCISE = 'SELECT_EXERCISE'
export const TOGGLE_CODONS = 'TOGGLE_CODONS'
export const EXERCISE_FAIL = 'EXERCISE_FAIL'
export const EXERCISE_SUCCESS = 'EXERCISE_SUCCESS'
export const NEW_EXERCISE = 'NEW_EXERCISE'

// admin exercise CRUD
export const ADD_EXERCISE = 'ADD_EXERCISE'
export const ADD_EXERCISE_INIT = 'ADD_EXERCISE_INIT'
export const ADD_EXERCISE_SUCCESS = 'ADD_EXERCISE_SUCCESS'
export const ADD_EXERCISE_FAIL = 'ADD_EXERCISE_FAIL§'
export const UPDATE_EXERCISE = 'UPDATE_EXERCISE'
export const UPDATE_EXERCISE_INIT = 'UPDATE_EXERCISE_INIT'
export const UPDATE_EXERCISE_SUCCESS = 'UPDATE_EXERCISE_SUCCESS'
export const UPDATE_EXERCISE_FAIL = 'UPDATE_EXERCISE_FAIL'
export const DELETE_EXERCISE = 'DELETE_EXERCISE'
export const DELETE_EXERCISE_INIT = 'DELETE_EXERCISE_INIT'
export const DELETE_EXERCISE_SUCCESS = 'DELETE_EXERCISE_SUCCESS'
export const DELETE_EXERCISE_FAIL = 'DELETE_EXERCISE_FAIL'

// notifications
export const NOTIFY_DELETED = 'NOTIFY_DELETED'

// admin filters
export const FILTER_EXERCISES_BY_TEXT = 'FILTER_EXERCISES_BY_TEXT'
export const SORT_EXERCISES_BY = 'SORT_EXERCISES_BY'
