export const RESites = [
  { 
    "seq": "AAGCTT", 
    "name": "HndIII", 
    "cutsForward": 1, 
    "cutsReverse": 5, 
    "color": "#a8ddb5",
    "len": 6,
  },
  { 
    "seq": "ACTAGT", 
    "name": "SpeI", 
    "cutsForward": 1, 
    "cutsReverse": 5, 
    "color": "#fdbb84",
    "len": 6, 
  },
  { 
    "seq": "CATATG", 
    "name": "NdeI", 
    "cutsForward": 2, 
    "cutsReverse": 4, 
    "color": "#95e2e2",
    "len": 6, 
  },
  { 
    "seq": "CCGCGG", 
    "name": "SacII", 
    "cutsForward": 4, 
    "cutsReverse": 2, 
    "color": "#43a2ca",
    "len": 6, 
  },
  { 
    "seq": "CTGCAG", 
    "name": "PstI", 
    "cutsForward": 5, 
    "cutsReverse": 1, 
    "color": "#fa9fb5",
    "len": 6, 
  },
  { 
    "seq": "GAATTC", 
    "name": "EcoRI", 
    "cutsForward": 1, 
    "cutsReverse": 5, 
    "color": "#e2959f",
    "len": 6, 
  },
  { 
    "seq": "GCTAGC", 
    "name": "NheI", 
    "cutsForward": 1, 
    "cutsReverse": 5, 
    "color": "#fca9dd",
    "len": 6, 
  },
  { 
    "seq": "GGTACC", 
    "name": "KpnI", 
    "cutsForward": 5, 
    "cutsReverse": 1, 
    "color": "#ea9fa8",
    "len": 6, 
  },
  { 
    "seq": "GTCGAC", 
    "name": "SalI", 
    "cutsForward": 1, 
    "cutsReverse": 5, 
    "color": "#dd904d",
    "len": 6, 
  },
  { 
    "seq": "TCTAGA", 
    "name": "Xba1", 
    "cutsForward": 1, 
    "cutsReverse": 5, 
    "color": "#ef6b6b",
    "len": 6, 
  },
  { 
    "seq": "CTCGAG", 
    "name": "Xho1", 
    "cutsForward": 1, 
    "cutsReverse": 5, 
    "color": "#746bb1",
    "len": 6, 
  },
  { 
    "seq": "GAGCTC", 
    "name": "Sac1", 
    "cutsForward": 5, 
    "cutsReverse": 1, 
    "color": "#cbcae2",
    "len": 6, 
  },
  { 
    "seq": "CCCGGG", 
    "name": "Sma1", 
    "cutsForward": 3, 
    "cutsReverse": 3, 
    "color": "#9b87c4",
    "len": 6, 
  },
  { 
    "seq": "CCATGG", 
    "name": "NcoI", 
    "cutsForward": 1, 
    "cutsReverse": 5, 
    "color": "#9db796",
    "len": 6, 
  }
]