export const RESites = [
  { 
    "seq": "AAGCTT", 
    "name": "HndIII", 
    "cutsForward": 1, 
    "cutsReverse": 5, 
    "color": "#eff75c",
    "len": 6,
  },
  { 
    "seq": "ACTAGT", 
    "name": "SpeI", 
    "cutsForward": 1, 
    "cutsReverse": 5, 
    "color": "#6050c5",
    "len": 6, 
  },
  { 
    "seq": "CATATG", 
    "name": "NdeI", 
    "cutsForward": 2, 
    "cutsReverse": 4, 
    "color": "#027a7a",
    "len": 6, 
  },
  { 
    "seq": "CCGCGG", 
    "name": "SacII", 
    "cutsForward": 4, 
    "cutsReverse": 2, 
    "color": "#67a77f",
    "len": 6, 
  },
  { 
    "seq": "CTGCAG", 
    "name": "PstI", 
    "cutsForward": 5, 
    "cutsReverse": 1, 
    "color": "#aa4fc3",
    "len": 6, 
  },
  { 
    "seq": "GAATTC", 
    "name": "EcoRI", 
    "cutsForward": 1, 
    "cutsReverse": 5, 
    "color": "#ac8a7a",
    "len": 6, 
  },
  { 
    "seq": "GCTAGC", 
    "name": "NheI", 
    "cutsForward": 1, 
    "cutsReverse": 5, 
    "color": "#ef2cef",
    "len": 6, 
  },
  { 
    "seq": "GGTACC", 
    "name": "KpnI", 
    "cutsForward": 5, 
    "cutsReverse": 1, 
    "color": "#30e3ed",
    "len": 6, 
  },
  { 
    "seq": "GTCGAC", 
    "name": "SalI", 
    "cutsForward": 1, 
    "cutsReverse": 5, 
    "color": "#dd904d",
    "len": 6, 
  },
  { 
    "seq": "TCTAGA", 
    "name": "Xba1", 
    "cutsForward": 1, 
    "cutsReverse": 5, 
    "color": "#bd5e7e",
    "len": 6, 
  },
  { 
    "seq": "CTCGAG", 
    "name": "Xho1", 
    "cutsForward": 1, 
    "cutsReverse": 5, 
    "color": "#eb3d4e",
    "len": 6, 
  },
  { 
    "seq": "GAGCTC", 
    "name": "Sac1", 
    "cutsForward": 5, 
    "cutsReverse": 1, 
    "color": "#a13c7c",
    "len": 6, 
  },
  { 
    "seq": "CCCGGG", 
    "name": "Sma1", 
    "cutsForward": 3, 
    "cutsReverse": 3, 
    "color": "#4f4367",
    "len": 6, 
  },
  { 
    "seq": "CCATGG", 
    "name": "NcoI", 
    "cutsForward": 1, 
    "cutsReverse": 5, 
    "color": "#eec6d3",
    "len": 6, 
  }
]